title:            Glendon Cheney
description:      This is the personal website and blog of Glendon Cheney, a software developer and musician.
disqus_shortname: gcheney
reading_time:     true 
words_per_minute: 200
logo:             images/logo.svg 
url: https://glendoncheney.com

menu:
  - title: 'Home'
    url: '/'
  - title: 'Projects'
    url: '/projects/'
  - title: 'Music'
    url: '/music/'
  - title: 'About'
    url: '/about/'
  - title: 'Contact'
    url: '/contact/'

# Owner/author information
owner:
  name: Glendon Cheney
  site: https://glendoncheney.com
  avatar: images/avatar-min.jpg
  bio: "I am a software developer and musician. Born, raised, and currently living in Austin, Texas."
  email: glendon@glendoncheney.com
  twitter: glendoncheney
  github: gcheney

# Twitter account associated with the site
twitter: 

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/gcheney"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/glendon-cheney-3a680926"
  - title: "soundcloud"
    url: "https://soundcloud.com/glencheney"
  - title: "twitter"
    url: "https://twitter.com/glendoncheney"
  - title: "imdb"
    url: "//www.imdb.com/name/nm3862321/"
    
# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools
google_analytics: true
google_verify:

timezone:    America/Chicago
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

#post permalinks
permalink:   :title/

# Amount of post to show on home page
paginate: 5
paginate_path: "/page:num/"

float_share: 

#Kramdown settings
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
