title:            Glendon Cheney
description:      This is the website and blog of Glendon Cheney, a software developer and musician from Austin.
# put your disqus here
disqus_shortname: gcheney
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.svg # logo visible in the topbar
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://glendoncheney.com

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'Projects'
    url: '/projects/'
  - title: 'About'
    url: '/about/'
  - title: 'Blog'
    url: '#'
    submenu:
      - title: 'All Posts'
        url: '/posts'
      - title: 'Categories'
        url: '/categories'
      - title: 'Tags'
        url: '/tags'



# Owner/author information
owner:
  name:           Glendon Cheney
  site:           https://www.glendoncheney.com
  avatar:         images/avatar-min.jpg
  bio:            "Full-stack web developer born, raised, and living in Austin, Texas."
  email:          glendon@glendoncheney.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: glendoncheney # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: gcheney

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: 

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/gcheney"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/glendon-cheney-3a680926"
  - title: "soundcloud"
    url: "https://soundcloud.com/glencheney"
  - title: "twitter"
    url: "https://twitter.com/glendoncheney"
  - title: "envelope"
    url: "mailto:glendon@glendoncheney.com"
# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   :title/

# Amount of post to show on home page
paginate: 5
paginate_path: "/page:num/"

# if true, shows the floatting share buttons
float_share: 

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
